
%Implantation d’une chaine de transmission
%utilisant une modulation de type ...
%Fr ́equence d’ ́echantillonnage
Fe=24000;
%D ́ebit binaire
Rb=3000;
%Niveau de Eb/N0 souhait ́e en dB
EbN0dB=10;
%Ordre de la modulation
M=2
%Fr ́equence porteuse
fp=2 ∗ 103;
%...
Te=1/Fe;
%...
Rs=Rb/log2(M);
%...
Ns=Fe/Rs;
%...
h=ones(1,Ns);
%...
hr=fliplr(h);
% G ́en ́eration de l’information binaire
bits=randi([0,1],1,1000);
% ...
ak=2*bits-1;
%...
diracs=kron(ak,[1 zeros(1,Ns-1)]);
%...
xe=filter(h,1,diracs);
%...
x=real(xe.*exp(j*2*pi*fp*[0:Te:(length(xe)-1)*Te]));
%...
Px=mean(abs(x). ˆ2);
%...
Pn=Px*Ns/(2*log2(M)*10 ˆ(EbN0dB/10));
%...
n=sqrt(Pn)*randn(1,length(x));
%...
r=x+n;
%...
z=filter(hr,1,r.* cos(2*pi*fp*[0:Te:(length(r)-1)*Te]));
%...
n0=Ns;
%...
zm=z(n0:Ns:end);
%...
am=sign(real(zm));
%...
bm=(am+1)/2;
%...
TEB=length(find((bm-bits) ~=0))/length(bits);